### ISSUE TITLE
Footer social media links should open in a new tab

### ISSUE THREAD

**Issue by ballaneypranav** [igembitsgoa/wiki#3]

**Comment by athete** [comment]
Hi, 
I fixed this issue by modifying the href tag by adding `target="_blank"` after the link.

I'll include it in the next PR that I send.
Danke

**Comment by ballaneypranav** [comment]
Thanks. You don't have to send another PR - when a PR is open it automatically adds all the commits.

**Comment by athete** [comment]
Oh no, I made the change after submitting the PR. That's why. But never mind, it works so no problem.

**Comment by ballaneypranav** [comment]
Yes, even then, as long as a PR is open, all commits just pile up there.
ᐧ
