### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ballaneypranav** [igembitsgoa/wiki#43]

**Comment by ballaneypranav** [comment]
Do we need a dark mode on the homepage?

**Comment by ballaneypranav** [comment]
- [x] Navbar background
- [x] Theme switch icons
- [x] Theme switch background
- [x] Body background
- [x] Contents section background
- [x] H1
- [x] Table
- [x] P tag
- [x] Other headings
- [x] In-text references 
- [x] Definition 
- [x] Buttons
- [ ] Footer links background
- [ ] Footer logo

**Comment by ballaneypranav** [comment]
JavaScript todo:

- [x] Detect theme from browser
- [x] Persistent dark mode across website

**Comment by athete** [comment]
> Do we need a dark mode on the homepage?

I don't think so. As it is, creating a dark mode will require us to create two versions of our graphics; I don't want to create extra work at the last minute.

**Comment by ballaneypranav** [comment]
> > Do we need a dark mode on the homepage?
> 
> I don't think so. As it is, creating a dark mode will require us to create two versions of our graphics; I don't want to create extra work at the last minute.

Yes let's just restrict it to content pages.
