### ISSUE TITLE
Pop out haikus

### ISSUE THREAD

**Issue by ballaneypranav** [igembitsgoa/wiki#62]
Don't really know how to do this

**Comment by athete** [comment]
Honestly, it looks fine even now. Do we really need this?

**Comment by ballaneypranav** [comment]
Looks good to me too, but Sharanya was saying it needs more work. I'll ask her.

**Comment by athete** [comment]
Not really required. I'm closing the issue now.

**Comment by SShastri19** [comment]
are we not popping them out then??
my idea was that instead of the optionnal hype, we could have the haikus in the other/contrasting colour

**Comment by athete** [comment]
Neither of us really knew what you meant by "pop-out". If it means using a contrasting colour, I think we could try that out. I'll reopen the issue then.

**Comment by ballaneypranav** [comment]
@SShastri19 Yes we discussed this on call that day but I forgot. Now that it's there in the issues, I'll remember.

**Comment by SShastri19** [comment]
![haikus layout](https://user-images.githubusercontent.com/55196785/92949453-bcdbdd80-f478-11ea-9490-72195e031aa5.png)
this was what i was thinking initially...
(also the pic quality is shit cause i worked this on a screenshot)

**Comment by ballaneypranav** [comment]
Yes this looks better
ᐧ
