### ISSUE TITLE
Notebook

### ISSUE THREAD

**Issue by ballaneypranav** [igembitsgoa/wiki#69]
- [x] Remove ToC
- [x] Vertical tabs for months 
- [x] Horizontal tabs for weeks

https://2019.igem.org/Team:Calgary/Notebook#top

**Comment by ballaneypranav** [comment]
Do we need images in the Notebook?

**Comment by athete** [comment]
We don't really have images of _anything_, forget observations. So no I guess.

**Comment by athete** [comment]
Commit 1fe850a412a306c2e8bc2b707cbce88ec38f5d30 resolves this. Marked closed.
